# Generated by Django 4.0.4 on 2022-05-11 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kumar', '0002_flipkart_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flipkart',
            name='age',
            field=models.IntegerField(max_length=50, null=True),
        ),
    ]
