# Generated by Django 4.0.4 on 2022-05-24 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kumar', '0004_morning'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flipkart',
            name='age',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='morning',
            name='dosa',
            field=models.CharField(max_length=50, null=True, verbose_name='dosa'),
        ),
        migrations.AlterField(
            model_name='morning',
            name='idly',
            field=models.CharField(max_length=50, null=True, verbose_name='idly'),
        ),
        migrations.AlterField(
            model_name='morning',
            name='pongal',
            field=models.CharField(max_length=50, null=True, verbose_name='pongal'),
        ),
        migrations.AlterField(
            model_name='morning',
            name='tea',
            field=models.CharField(max_length=50, verbose_name='tea'),
        ),
    ]
