# Generated by Django 4.0.4 on 2022-05-24 06:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kumar', '0006_admin'),
    ]

    operations = [
        migrations.CreateModel(
            name='items',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Item Name')),
            ],
            options={
                'verbose_name': 'items',
                'verbose_name_plural': 'items',
            },
        ),
        migrations.RemoveField(
            model_name='morning',
            name='dosa',
        ),
        migrations.RemoveField(
            model_name='morning',
            name='idly',
        ),
        migrations.RemoveField(
            model_name='morning',
            name='pongal',
        ),
        migrations.RemoveField(
            model_name='morning',
            name='tea',
        ),
        migrations.AddField(
            model_name='morning',
            name='morning_item',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kumar.items', verbose_name='tea'),
            preserve_default=False,
        ),
    ]
