# Generated by Django 4.0.4 on 2022-05-24 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kumar', '0007_items_remove_morning_dosa_remove_morning_idly_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morning',
            name='morning_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kumar.items', verbose_name='Morning Item'),
        ),
    ]
