# Generated by Django 4.0.4 on 2022-05-24 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kumar', '0008_alter_morning_morning_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='morningitems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idly', models.CharField(max_length=50, null=True)),
                ('dosa', models.CharField(max_length=50, null=True)),
                ('tea', models.CharField(max_length=50, null=True)),
                ('pongal', models.CharField(max_length=50, null=True)),
            ],
            options={
                'verbose_name': 'morningitems',
                'verbose_name_plural': 'morningitemss',
            },
        ),
    ]
